#Need auth_code for URL Redirect. This script will run ONCE to provide the Auth_Token for the Next part.

import http.client
import json
import urllib.parse

def get_tokens(client_id, client_secret, redirect_uri, auth_code):
    conn = http.client.HTTPSConnection("accounts.zoho.com")
    params = {
        'code': auth_code,
        'redirect_uri': redirect_uri,
        'client_id': client_id,
        'client_secret': client_secret,
        'grant_type': 'authorization_code'
    }
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    conn.request("POST", "/oauth/v2/token", urllib.parse.urlencode(params), headers)
    response = conn.getresponse()
    response_data = response.read()
    tokens = json.loads(response_data.decode("utf-8"))
    return tokens

# Replace these with your actual details
client_id = '1000.abc123
client_secret = abc123
redirect_uri = 'https://www.abc123.com'
#Below is the code generated by "Auth Code" and needs to go to Keeebs.com to get the number.
auth_code = '1000.abc123'



tokens = get_tokens(client_id, client_secret, redirect_uri, auth_code)
print(tokens)  # tokens will contain both access_token and refresh_token
ient_id, client_secret, redirect_uri, auth_code)
print(tokens)  # tokens will contain both access_token and refresh_token
